apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderealm-client
  namespace: coderealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coderealm-client
  template:
    metadata:
      labels:
        app: coderealm-client
    spec:
      containers:
      - name: coderealm-client
        image: lokeshkatari/coderealm-client:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: GRPC_SERVER
          value: "code-exec-service.coderealm.svc.cluster.local"    
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
