apiVersion: apps/v1
kind: Deployment
metadata:
  name: coderealm-client
  namespace: coderealm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coderealm-client
  template:
    metadata:
      labels:
        app: coderealm-client
    spec:
      containers:
      - name: coderealm-client
        image: lokeshkatari/coderealm-client:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9092
        - name: GRPC_URI_CODE_CLIENT
          value: "code-exec-service.coderealm:50052"  
        - name : REDIS_URI
          value: "redis://default:vjIGMyBfPrVKyR1l7F12Gf0SxvHofMmq@redis-10614.c13.us-east-1-3.ec2.cloud.redislabs.com:10614"  
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
