apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: code-client
  name: code-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: code-client
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kafka-network: "true"
        io.kompose.service: code-client
    spec:
      containers:
        - image: lokeshkatari/coderealm-client
          name: code-client
      restartPolicy: Always
